# Generated by Django 5.0.3 on 2024-04-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diario',
            options={},
        ),
    ]
