# Generated by Django 5.0.4 on 2024-05-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorfile',
            name='archive',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
