# Generated by Django 5.0.4 on 2024-05-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='professor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
