# Generated by Django 5.0.3 on 2024-04-04 11:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='problem',
        ),
        migrations.RemoveField(
            model_name='question',
            name='have_tried',
        ),
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(default=datetime.date),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cc.disciplina')),
            ],
            options={
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
