# Generated by Django 5.0.4 on 2024-04-23 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_cc", "0002_aluno_usuario_alter_professor_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="nome",
        ),
    ]
