# Generated by Django 5.0.4 on 2024-05-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='app_cc.aluno'),
        ),
        migrations.AlterField(
            model_name='file',
            name='archive',
            field=models.ImageField(upload_to=''),
        ),
    ]
