# Generated by Django 5.0.4 on 2024-04-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0002_alter_diario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='disciplina',
            field=models.CharField(max_length=50),
        ),
    ]
