# Generated by Django 5.0.4 on 2024-05-24 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0002_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cc.professor'),
        ),
    ]
