# Generated by Django 5.0.4 on 2024-05-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0002_aluno_foto_perfil_professor_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
