# Generated by Django 5.0.4 on 2024-05-01 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0002_alter_nota_valor_falta'),
    ]

    operations = [
        migrations.AddField(
            model_name='falta',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='app_cc.disciplina'),
        ),
    ]
