# Generated by Django 5.0.4 on 2024-05-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0002_alter_professorfile_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorfile',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
