# Generated by Django 5.0.4 on 2024-05-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0003_aviso_alter_evento_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='imagem',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
