# Generated by Django 5.0.4 on 2024-05-31 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0003_professorfile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorfile',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cc.disciplina'),
        ),
    ]
