# Generated by Django 5.0.4 on 2024-05-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0003_file_aluno_alter_file_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='horas_extras',
            field=models.FloatField(default=0),
        ),
    ]
