# Generated by Django 5.0.4 on 2024-05-31 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0004_professorfile_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorfile',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='app_cc.disciplina'),
        ),
    ]
