# Generated by Django 5.0.6 on 2024-06-22 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='data_ocorrencia',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
