# Generated by Django 5.0.6 on 2024-06-25 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cc', '0009_like_post_curtidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='arquivos_atividades/%Y/%m/%d/', verbose_name='Arquivo')),
                ('texto', models.TextField(default='Essa atividade não possui descrição.', verbose_name='Texto')),
                ('titulo', models.CharField(default='Essa atividade não possui título', max_length=500, verbose_name='Título')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cc.disciplina', verbose_name='Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cc.professor', verbose_name='professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cc.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='AtividadeFeita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusao', models.BooleanField(default=False, verbose_name='A atividade foi feita?')),
                ('arquivo', models.FileField(upload_to='atividades_alunos/%Y/%m/%d/', verbose_name='Arquivo')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cc.aluno', verbose_name='Aluno')),
                ('atividade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_cc.atividade', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Qual atividade foi feita?',
                'verbose_name_plural': 'Quais atividades foram feitas?',
            },
        ),
    ]
